# Generated by Django 4.0.3 on 2023-01-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='color',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='href',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='picture_url',
            field=models.URLField(null=True),
        ),
    ]
