# Generated by Django 4.0.3 on 2023-01-23 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_remove_automobilevo_color_automobilevo_href_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='model',
            new_name='name',
        ),
    ]
