# Generated by Django 4.0.3 on 2023-01-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
