# Generated by Django 4.0.3 on 2023-01-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='sales_price',
        ),
    ]
